gui:
  theme:
    activeBorderColor:
      - "#c4a7e7"
      - bold
    inactiveBorderColor:
      - "#44415a"
    searchingActiveBorderColor:
      - "#c4a7e7"
      - bold
    optionsTextColor:
      - "#9ccfd8"
    selectedLineBgColor:
      - "#2a273f"
    selectedRangeBgColor:
      - "#2a273f"
    cherryPickedCommitBgColor:
      - "#44415a"
    cherryPickedCommitFgColor:
      - "#c4a7e7"
    unstagedChangesColor:
      - "#eb6f92"
    defaultFgColor:
      - "#e0def4"
  nerdFontsVersion: "3"
